const express = require("express");
const cors = require("cors");

const app = express();
app.use(cors());


const frasesRomanticas = [
"Você é meu sorriso favorito.",
"Cada dia contigo é um presente.",
"Meu coração é seu.",
"Você me faz querer ser melhor.",
"Te amar é minha paz.",
"Cada instante ao seu lado é mágico.",
"Você é meu porto seguro.",
"Amo cada detalhe seu.",
"Você é meu sonho realizado.",
"Com você, tudo faz sentido.",
"Te quero em todos os meus dias.",
"Meu coração bate por você.",
"Você ilumina meus dias.",
"Amor assim é infinito.",
"Só você me entende de verdade.",
"Cada abraço seu é lar.",
"Te amar é minha felicidade.",
"Você é minha melhor escolha.",
"Meu mundo é mais colorido contigo.",
"Você é minha inspiração diária.",
"Amar você é natural.",
"Meu coração sorri quando penso em você.",
"Você é minha alegria constante.",
"Teu sorriso é meu vício.",
"Amo você mais a cada dia.",
"Você é meu amor eterno.",
"Com você, tudo é possível.",
"Teu abraço é meu refúgio.",
"Você é minha paz e tempestade.",
"Amar você é fácil.",
"Você é meu tesouro mais precioso.",
"Meu mundo começou quando te conheci.",
"Teu amor me transforma.",
"Amo a forma como me faz sentir.",
"Você é meu para sempre.",
"Com você, sou completo.",
"Te amar é respirar.",
"Meu coração é feliz por sua causa.",
"Você é meu raio de sol.",
"Amo a forma como sorrimos juntos.",
"Você é minha canção favorita.",
"Cada olhar seu me encanta.",
"Amar você é minha maior aventura.",
"Você é meu melhor pensamento do dia.",
"Com você, todos os dias são especiais.",
"Você me faz acreditar no amor.",
"Meu amor por você não tem fim.",
"Cada momento ao seu lado é eterno.",
"Você é minha melhor metade.",
"Te amo mais do que palavras podem dizer.",
"Você faz meu coração dançar.",
"Amo você em cada detalhe.",
"Cada segundo contigo é mágico.",
"Você é meu motivo de felicidade.",
"Meu coração encontrou lar em você.",
"Teu sorriso ilumina minha vida.",
"Amar você é minha rotina favorita.",
"Você é meu sonho constante.",
"Meu mundo é melhor contigo.",
"Você é minha inspiração diária.",
"Cada abraço seu me conforta.",
"Amo cada gesto seu.",
"Você é minha alegria infinita.",
"Te amar é minha força.",
"Meu coração escolheu você.",
"Você é meu céu estrelado.",
"Amar você é respirar fundo de felicidade.",
"Cada olhar seu me fascina.",
"Você é meu refúgio seguro.",
"Teu amor me transforma.",
"Amo tudo em você.",
"Você é meu presente diário.",
"Meu coração pulsa por você.",
"Você é minha razão de sorrir.",
"Amar você é meu destino.",
"Cada momento contigo é especial.",
"Você é meu para sempre.",
"Meu mundo começou com você.",
"Você é meu raio de sol constante.",
"Amar você é minha paz.",
"Cada beijo seu é um sonho.",
"Você é minha metade perfeita.",
"Meu coração é seu lar.",
"Te amar é minha alegria.",
"Você é minha eternidade.",
"Cada instante contigo vale ouro.",
"Você é meu porto seguro eterno.",
"Meu amor cresce a cada dia.",
"Você é meu motivo de viver.",
"Amar você é minha aventura favorita.",
"Cada palavra sua é poesia.",
"Você é meu céu e minha estrela.",
"Meu coração sorri por você.",
"Te amar é minha música favorita.",
"Você é meu abraço quente.",
"Cada gesto seu me encanta.",
"Você é meu sonho real.",
"Meu amor por você não tem fim.",
"Você é minha alegria diária.",
"Cada abraço seu é meu lar.",
"Amar você é respirar felicidade.",
"Você é meu melhor presente.",
"Meu coração é feliz por você.",
"Você é minha luz constante.",
"Cada momento contigo é precioso.",
"Você é meu mundo colorido.",
"Te amar é minha rotina favorita.",
"Você é meu eterno encanto.",
"Meu coração pulsa só por você.",
"Você é meu refúgio seguro.",
"Cada sorriso seu é meu paraíso.",
"Você é meu sonho realizado.",
"Amar você é minha calmaria.",
"Você é meu porto seguro.",
"Meu amor por você é infinito.",
"Cada beijo seu é magia.",
"Você é minha inspiração constante.",
"Te amar é minha maior felicidade.",
"Você é meu lar eterno.",
"Cada dia contigo é um tesouro.",
"Você é meu céu estrelado.",
"Amar você é minha aventura diária.",
"Você é meu raio de sol.",
"Meu coração é seu.",
"Você é minha metade perfeita.",
"Cada olhar seu me emociona.",
"Você é minha paz infinita.",
"Amar você é meu refúgio.",
"Você é meu sonho diário.",
"Meu amor cresce com você.",
"Cada abraço seu me aquece.",
"Você é meu presente constante.",
"Te amar é meu destino feliz.",
"Você é minha razão de viver.",
"Meu coração encontrou lar em você.",
"Você é minha eternidade.",
"Cada palavra sua é poesia.",
"Você é meu melhor pensamento.",
"Amar você é minha calmaria.",
"Você é meu raio de luz.",
"Meu amor por você é imenso.",
"Cada instante contigo é único.",
"Você é meu lar seguro.",
"Te amar é meu refúgio eterno.",
"Você é minha alegria infinita.",
"Cada beijo seu é felicidade.",
"Você é meu mundo completo.",
"Meu coração é seu tesouro.",
"Você é minha estrela guia.",
"Amar você é minha aventura favorita.",
"Você é meu céu e minha lua.",
"Cada abraço seu é meu lar seguro.",
"Você é meu sonho realizado.",
"Meu amor por você não tem fim.",
"Você é minha paz diária.",
"Cada olhar seu me ilumina.",
"Você é meu porto seguro.",
"Te amar é minha maior alegria.",
"Você é meu eterno encanto.",
"Meu coração bate só por você.",
"Cada instante contigo é mágico.",
"Você é meu sol radiante.",
"Amar você é minha felicidade.",
"Você é meu mundo colorido.",
"Meu amor cresce a cada dia.",
"Cada gesto seu me toca.",
"Você é meu presente eterno.",
"Te amar é minha calmaria.",
"Você é minha luz constante.",
"Meu coração escolheu você.",
"Cada beijo seu é poesia.",
"Você é meu sonho constante.",
"Amar você é respirar alegria.",
"Você é meu refúgio seguro.",
"Cada sorriso seu me ilumina.",
"Você é minha razão de viver.",
"Meu amor é todo seu.",
"Você é minha metade perfeita.",
"Cada abraço seu é lar.",
"Você é meu céu estrelado.",
"Te amar é minha música favorita.",
"Você é meu raio de sol.",
"Meu coração é feliz por você.",
"Cada momento contigo é especial.",
"Você é meu eterno encanto.",
"Amar você é minha maior aventura.",
"Você é meu tesouro diário.",
"Meu amor cresce por você.",
"Cada olhar seu me fascina.",
"Você é minha paz infinita.",
"Te amar é meu presente diário.",
"Você é meu lar eterno.",
"Cada palavra sua é magia.",
"Você é meu sonho real.",
"Meu coração bate por você.",
"Você é minha alegria diária.",
"Cada instante contigo é ouro.",
"Você é meu porto seguro.",
"Amar você é minha calmaria.",
"Você é meu mundo colorido.",
"Meu amor por você é infinito.",
"Cada gesto seu me encanta.",
"Você é meu presente constante.",
"Te amar é minha aventura favorita.",
"Você é minha luz e guia.",
"Meu coração escolheu você.",
"Cada beijo seu é meu lar.",
"Você é meu sonho diário.",
"Amar você é respirar felicidade.",
"Você é meu refúgio seguro.",
"Cada sorriso seu ilumina meu dia.",
"Você é minha razão de sorrir.",
"Meu amor cresce a cada instante.",
"Você é minha metade perfeita.",
"Cada abraço seu é magia.",
"Você é meu céu estrelado.",
"Te amar é minha maior alegria.",
"Você é meu raio de sol constante.",
"Meu coração é seu para sempre.",
"Cada momento contigo é especial.",
"Você é meu presente diário.",
"Amar você é minha paz.",
"Você é meu lar seguro.",
"Meu amor por você não tem fim.",
"Cada olhar seu me toca.",
"Você é minha felicidade constante.",
"Te amar é minha aventura diária.",
"Você é meu eterno encanto.",
"Meu coração bate só por você.",
"Cada instante contigo é precioso.",
"Você é meu sol radiante.",
"Amar você é minha calma e alegria.",
"Você é meu mundo completo.",
"Meu amor cresce a cada dia.",
"Cada gesto seu me emociona.",
"Você é meu presente eterno.",
"Te amar é minha maior felicidade.",
"Você é minha luz constante.",
"Meu coração escolheu você.",
"Cada beijo seu é poesia.",
"Você é meu sonho constante.",
"Amar você é respirar felicidade.",
"Você é meu refúgio seguro.",
"Cada sorriso seu me ilumina.",
"Você é minha razão de viver.",
"Meu amor é todo seu.",
"Você é minha metade perfeita.",
"Cada abraço seu é lar.",
"Você é meu céu estrelado.",
"Te amar é minha música favorita.",
"Você é meu raio de sol.",
"Meu coração é feliz por você.",
"Cada momento contigo é especial.",
"Você é meu eterno encanto.",
"Amar você é minha maior aventura.",
"Você é meu tesouro diário.",
"Meu amor cresce por você.",
"Cada olhar seu me fascina.",
"Você é minha paz infinita.",
"Te amar é meu presente diário.",
"Você é meu lar eterno.",
"Cada palavra sua é magia.",
"Você é meu sonho real.",
"Meu coração bate por você.",
"Você é minha alegria diária.",
"Cada instante contigo é ouro.",
"Você é meu porto seguro.",
"Amar você é minha calmaria.",
"Você é meu mundo colorido.",
"Meu amor por você é infinito.",
"Cada gesto seu me encanta.",
"Você é meu presente constante.",
"Te amar é minha aventura favorita.",
"Você é minha luz e guia.",
"Meu coração escolheu você.",
"Cada beijo seu é meu lar.",
"Você é meu sonho diário.",
"Amar você é respirar felicidade.",
"Você é meu refúgio seguro.",
"Cada sorriso seu ilumina meu dia.",
"Você é minha razão de sorrir.",
"Meu amor cresce a cada instante.",
"Você é minha metade perfeita.",
"Cada abraço seu é magia.",
"Você é meu céu estrelado.",
"Te amar é minha maior alegria.",
"Você é meu raio de sol constante.",
"Meu coração é seu para sempre.",
"Cada momento contigo é especial.",
"Você é meu presente diário.",
"Amar você é minha paz.",
"Você é meu lar seguro.",
"Meu amor por você não tem fim.",
"Cada olhar seu me toca.",
"Você é minha felicidade constante.",
"Te amar é minha aventura diária.",
"Você é meu eterno encanto.",
"Meu coração bate só por você.",
"Cada instante contigo é precioso.",
"Você é meu sol radiante.",
"Amar você é minha calma e alegria.",
"Você é meu mundo completo.",
"Meu amor cresce a cada dia.",
"Cada gesto seu me emociona.",
"Você é meu presente eterno.",
"Te amar é minha maior felicidade.",
"Você é minha luz constante.",
"Meu coração escolheu você.",
"Cada beijo seu é poesia.",
"Você é meu sonho constante.",
"Amar você é respirar felicidade.",
"Você é meu refúgio seguro.",
"Cada sorriso seu me ilumina.",
"Você é minha razão de viver.",
"Meu amor é todo seu.",
"Você é minha metade perfeita.",
"Cada abraço seu é lar.",
"Você é meu céu estrelado.",
"Te amar é minha música favorita.",
"Você é meu raio de sol.",
"Meu coração é feliz por você.",
"Cada momento contigo é especial.",
"Você é meu eterno encanto.",
"Amar você é minha maior aventura.",
"Você é meu tesouro diário.",
"Meu amor cresce por você.",
"Cada olhar seu me fascina.",
"Você é minha paz infinita.",
"Te amar é meu presente diário.",
"Você é meu lar eterno.",
"Cada palavra sua é magia.",
"Você é meu sonho real.",
"Meu coração bate por você.",
"Você é minha alegria diária.",
"Cada instante contigo é ouro.",
"Você é meu porto seguro.",
"Amar você é minha calmaria.",
"Você é meu mundo colorido.",
"Meu amor por você é infinito.",
"Cada gesto seu me encanta.",
"Você é meu presente constante.",
"Te amar é minha aventura favorita.",
"Você é minha luz e guia.",
"Meu coração escolheu você.",
"Cada beijo seu é meu lar.",
"Você é meu sonho diário.",
"Amar você é respirar felicidade.",
"Você é meu refúgio seguro.",
"Cada sorriso seu ilumina meu dia.",
"Você é minha razão de sorrir.",
"Meu amor cresce a cada instante.",
"Você é minha metade perfeita.",
"Cada abraço seu é magia.",
"Você é meu céu estrelado.",
"Te amar é minha maior alegria.",
"Você é meu raio de sol constante.",
"Meu coração é seu para sempre.",
"Cada momento contigo é especial.",
"Você é meu presente diário.",
"Amar você é minha paz.",
"Você é meu lar seguro.",
"Meu amor por você não tem fim.",
"Cada olhar seu me toca.",
"Você é minha felicidade constante.",
"Te amar é minha aventura diária.",
"Você é meu eterno encanto.",
"Meu coração bate só por você.",
"Cada instante contigo é precioso.",
"Você é meu sol radiante.",
"Amar você é minha calma e alegria.",
"Você é meu mundo completo.",
"Meu amor cresce a cada dia.",
"Cada gesto seu me emociona.",
"Você é meu presente eterno.",
"Te amar é minha maior felicidade.",
"Você é minha luz constante.",
"Meu coração escolheu você.",
"Cada beijo seu é poesia.",
"Você é meu sonho constante.",
"Amar você é respirar felicidade.",
"Você é meu refúgio seguro.",
"Cada sorriso seu me ilumina.",
"Você é minha razão de viver.",
"Meu amor é todo seu.",
"Você é minha metade perfeita.",
"Cada abraço seu é lar.",
"Você é meu céu estrelado.",
"Te amar é minha música favorita.",
"Você é meu raio de sol.",
"Meu coração é feliz por você.",
"Cada momento contigo é especial.",
"Você é meu eterno encanto."
];

console.log(frasesRomanticas.length); // Deve retornar 365


// Função para pegar a frase do dia
function fraseDoDia() {
  const hoje = new Date();
  const diaDoAno = Math.floor(
    (hoje - new Date(hoje.getFullYear(), 0, 0)) / (1000 * 60 * 60 * 24)
  );
  return frases[diaDoAno % frases.length];
}

// Rota principal
app.get("/frase", (req, res) => {
  res.json({ frase: fraseDoDia() });
});

// Iniciar servidor
const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
  console.log(`Servidor rodando na porta ${PORT}`);
});


